//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileCaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileCaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add diapason.
        /// </summary>
        internal static string BTN_ADD_DIAPASON {
            get {
                return ResourceManager.GetString("BTN_ADD_DIAPASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group..
        /// </summary>
        internal static string BTN_ADD_GROUP_HINT {
            get {
                return ResourceManager.GetString("BTN_ADD_GROUP_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling.
        /// </summary>
        internal static string BTN_CALL {
            get {
                return ResourceManager.GetString("BTN_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop calling.
        /// </summary>
        internal static string BTN_CALL_STOP {
            get {
                return ResourceManager.GetString("BTN_CALL_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string BTN_ENTER {
            get {
                return ResourceManager.GetString("BTN_ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open working directory.
        /// </summary>
        internal static string BTN_OPEN_WORKING_DIRECTORY_HINT {
            get {
                return ResourceManager.GetString("BTN_OPEN_WORKING_DIRECTORY_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Group.
        /// </summary>
        internal static string BTN_REMOVE_GROUP_HINT {
            get {
                return ResourceManager.GetString("BTN_REMOVE_GROUP_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BTN_SEARCH {
            get {
                return ResourceManager.GetString("BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string CB_GROUP_FILTER_ALL {
            get {
                return ResourceManager.GetString("CB_GROUP_FILTER_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string L_ALL_RIGHTS_RESERVED {
            get {
                return ResourceManager.GetString("L_ALL_RIGHTS_RESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2012-2014 Taycoon.
        /// </summary>
        internal static string L_COPYRIGHT {
            get {
                return ResourceManager.GetString("L_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number to search:.
        /// </summary>
        internal static string L_ENTER_SEARCHED_PHONE {
            get {
                return ResourceManager.GetString("L_ENTER_SEARCHED_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group filter.
        /// </summary>
        internal static string L_GROUP_FILTER {
            get {
                return ResourceManager.GetString("L_GROUP_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound.
        /// </summary>
        internal static string L_PLAY_SOUND {
            get {
                return ResourceManager.GetString("L_PLAY_SOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound when call is finished.\nPlease check that sound is turned on your operation system..
        /// </summary>
        internal static string L_PLAY_SOUND_HINT {
            get {
                return ResourceManager.GetString("L_PLAY_SOUND_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string L_PORT {
            get {
                return ResourceManager.GetString("L_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com port number, to what mobile phone is connected.\nOperation system uses virtual Com port for mobile connections through USB..
        /// </summary>
        internal static string L_PORT_HINT {
            get {
                return ResourceManager.GetString("L_PORT_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem is not responding on AT commands..
        /// </summary>
        internal static string L_PORT_INFORMATION_MODEM_NOT_ANSWERED {
            get {
                return ResourceManager.GetString("L_PORT_INFORMATION_MODEM_NOT_ANSWERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no selected modem to work with..
        /// </summary>
        internal static string L_PORT_INFORMATION_MODEM_NOT_SELECTED {
            get {
                return ResourceManager.GetString("L_PORT_INFORMATION_MODEM_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem is ready to work..
        /// </summary>
        internal static string L_PORT_INFORMATION_MODEM_SELECTED {
            get {
                return ResourceManager.GetString("L_PORT_INFORMATION_MODEM_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        internal static string L_PORT_RATE {
            get {
                return ResourceManager.GetString("L_PORT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com port baud rate.\nIt&apos;s presented in &apos;Device Manager&apos; for your modem of mobile phone..
        /// </summary>
        internal static string L_PORT_RATE_HINT {
            get {
                return ResourceManager.GetString("L_PORT_RATE_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of MobileCaller : {0}.
        /// </summary>
        internal static string L_PROGRAM_VERSION {
            get {
                return ResourceManager.GetString("L_PROGRAM_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter activation key.
        /// </summary>
        internal static string L_REGISTERED_ACTIVATION_KEY {
            get {
                return ResourceManager.GetString("L_REGISTERED_ACTIVATION_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail.
        /// </summary>
        internal static string L_REGISTERED_EMAIL {
            get {
                return ResourceManager.GetString("L_REGISTERED_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IMEI.
        /// </summary>
        internal static string L_REGISTERED_IMEI {
            get {
                return ResourceManager.GetString("L_REGISTERED_IMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string L_REGISTERED_USER {
            get {
                return ResourceManager.GetString("L_REGISTERED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter registration data and received activation key.
        /// </summary>
        internal static string L_REGISTRATION_INVITATION {
            get {
                return ResourceManager.GetString("L_REGISTRATION_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Activation key is applied to one IMEI of mobile phone. In case you need to work with several mobile phones you should start several program instances with each licence owned by special mobile phone..
        /// </summary>
        internal static string L_REGISTRATION_WARNING {
            get {
                return ResourceManager.GetString("L_REGISTRATION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeatable.
        /// </summary>
        internal static string L_REPEATABLE {
            get {
                return ResourceManager.GetString("L_REPEATABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable repeatable mode of call.\nStart call process again when current one is finished..
        /// </summary>
        internal static string L_REPEATABLE_HINT {
            get {
                return ResourceManager.GetString("L_REPEATABLE_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification.
        /// </summary>
        internal static string L_SEND_NOTIFICATION {
            get {
                return ResourceManager.GetString("L_SEND_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification (SMS or USSD) after successfully activated phone number..
        /// </summary>
        internal static string L_SEND_NOTIFICATION_HINT {
            get {
                return ResourceManager.GetString("L_SEND_NOTIFICATION_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown PC.
        /// </summary>
        internal static string L_SHUTDOWN {
            get {
                return ResourceManager.GetString("L_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown PC after call is finished with preceding saving all changes and exit from application..
        /// </summary>
        internal static string L_SHUTDOWN_HINT {
            get {
                return ResourceManager.GetString("L_SHUTDOWN_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductory version.
        /// </summary>
        internal static string L_USER {
            get {
                return ResourceManager.GetString("L_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait call.
        /// </summary>
        internal static string L_WAIT_CALL {
            get {
                return ResourceManager.GetString("L_WAIT_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time to wait in seconds between calls and sending of notifications.\nIt is used in case when operator blocks card, thinking that it&apos;s behaviour is suspicious..
        /// </summary>
        internal static string L_WAIT_CALL_HINT {
            get {
                return ResourceManager.GetString("L_WAIT_CALL_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory.
        /// </summary>
        internal static string L_WORKING_DIRECTORY {
            get {
                return ResourceManager.GetString("L_WORKING_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory containing logging files of program\nin the format of Log&lt;Year&gt;_&lt;Month&gt;_&lt;Day&gt;.txt,\nregistering file and settings with base of phones..
        /// </summary>
        internal static string L_WORKING_DIRECTORY_HINT {
            get {
                return ResourceManager.GetString("L_WORKING_DIRECTORY_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call process is finished..
        /// </summary>
        internal static string LOG_CALL_FINISHED {
            get {
                return ResourceManager.GetString("LOG_CALL_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call process is finished. Restarted..
        /// </summary>
        internal static string LOG_CALL_RESTARTED {
            get {
                return ResourceManager.GetString("LOG_CALL_RESTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} notifications are sent..
        /// </summary>
        internal static string LOG_NOTIFICATION_FINISHED {
            get {
                return ResourceManager.GetString("LOG_NOTIFICATION_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Number {0} was sent in black list. Dialing time: {1}. Ringing time: {2}..
        /// </summary>
        internal static string LOG_NUMBER_BLACKLISTED {
            get {
                return ResourceManager.GetString("LOG_NUMBER_BLACKLISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured at processing of number {0}. Dialing time: {1}. Ringing time: {2}..
        /// </summary>
        internal static string LOG_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("LOG_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Modem is not answered on command. Dialing time: {1}. Ringing time: {2}..
        /// </summary>
        internal static string LOG_NUMBER_NO_ANSWER_MODEM {
            get {
                return ResourceManager.GetString("LOG_NUMBER_NO_ANSWER_MODEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number {0} is processed. Dialing time: {1}. Ringing time: {2}..
        /// </summary>
        internal static string LOG_NUMBER_PROCESSED {
            get {
                return ResourceManager.GetString("LOG_NUMBER_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed: {0}. Found: {1}..
        /// </summary>
        internal static string LOG_STATISTICS {
            get {
                return ResourceManager.GetString("LOG_STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double check.
        /// </summary>
        internal static string LST_DOUBLE_CHECK_ON_TIMEOUT {
            get {
                return ResourceManager.GetString("LST_DOUBLE_CHECK_ON_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables double check of phone number in case it was found as activated by mode &apos;{0}&apos;.\nIt is required when connection through mobile operator line has interruption by time and is not stable..
        /// </summary>
        internal static string LST_DOUBLE_CHECK_ON_TIMEOUT_HINT {
            get {
                return ResourceManager.GetString("LST_DOUBLE_CHECK_ON_TIMEOUT_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string LST_GROUP_NAME {
            get {
                return ResourceManager.GetString("LST_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name of operator which should be called through..
        /// </summary>
        internal static string LST_GROUP_NAME_HINT {
            get {
                return ResourceManager.GetString("LST_GROUP_NAME_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group name.
        /// </summary>
        internal static string LST_GROUP_NAME_NEW {
            get {
                return ResourceManager.GetString("LST_GROUP_NAME_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type.
        /// </summary>
        internal static string LST_NOTIFICATION_TYPE {
            get {
                return ResourceManager.GetString("LST_NOTIFICATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose notification type which will be used for activated phone number found..
        /// </summary>
        internal static string LST_NOTIFICATION_TYPE_HINT {
            get {
                return ResourceManager.GetString("LST_NOTIFICATION_TYPE_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS number.
        /// </summary>
        internal static string LST_SMS_RECIPIENT {
            get {
                return ResourceManager.GetString("LST_SMS_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number which needs to be recipient of SMS for activated number from group number list..
        /// </summary>
        internal static string LST_SMS_RECIPIENT_HINT {
            get {
                return ResourceManager.GetString("LST_SMS_RECIPIENT_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of SMS.
        /// </summary>
        internal static string LST_SMS_TEXT {
            get {
                return ResourceManager.GetString("LST_SMS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of SMS sent after number is activated.\nUse %PHONE% template to substitute it in the text by the number to be called..
        /// </summary>
        internal static string LST_SMS_TEXT_HINT {
            get {
                return ResourceManager.GetString("LST_SMS_TEXT_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string LST_TELEPHONES_COMMENT {
            get {
                return ResourceManager.GetString("LST_TELEPHONES_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input date.
        /// </summary>
        internal static string LST_TELEPHONES_DATE {
            get {
                return ResourceManager.GetString("LST_TELEPHONES_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation date.
        /// </summary>
        internal static string LST_TELEPHONES_DATE_ACTIVATION {
            get {
                return ResourceManager.GetString("LST_TELEPHONES_DATE_ACTIVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string LST_TELEPHONES_NUMBER {
            get {
                return ResourceManager.GetString("LST_TELEPHONES_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of USSD request.
        /// </summary>
        internal static string LST_USSD_TEXT {
            get {
                return ResourceManager.GetString("LST_USSD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of USSD sent after number is activated.\nUse %PHONE% template to substitute it in the text by the number to be called..
        /// </summary>
        internal static string LST_USSD_TEXT_HINT {
            get {
                return ResourceManager.GetString("LST_USSD_TEXT_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait answer.
        /// </summary>
        internal static string LST_WAIT_ANSWER {
            get {
                return ResourceManager.GetString("LST_WAIT_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait answer in seconds of ending call response &apos;Number is not serviced&apos;.\nIt&apos;s needed to distinguish such answers like &apos;Number is out of zone&apos;, etc.\nSets the yellow color for activated phone number found..
        /// </summary>
        internal static string LST_WAIT_ANSWER_HINT {
            get {
                return ResourceManager.GetString("LST_WAIT_ANSWER_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MI_ABOUT {
            get {
                return ResourceManager.GetString("MI_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call latest.
        /// </summary>
        internal static string MI_CALL_LATEST {
            get {
                return ResourceManager.GetString("MI_CALL_LATEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call selected.
        /// </summary>
        internal static string MI_CALL_SELECTED {
            get {
                return ResourceManager.GetString("MI_CALL_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string MI_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("MI_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        internal static string MI_DELETE_SELECTED {
            get {
                return ResourceManager.GetString("MI_DELETE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MI_EDIT {
            get {
                return ResourceManager.GetString("MI_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MI_EXIT {
            get {
                return ResourceManager.GetString("MI_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MI_FILE {
            get {
                return ResourceManager.GetString("MI_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        internal static string MI_HELP {
            get {
                return ResourceManager.GetString("MI_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string MI_IMPORT {
            get {
                return ResourceManager.GetString("MI_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MI_INFORMATION {
            get {
                return ResourceManager.GetString("MI_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MI_LANGUAGE {
            get {
                return ResourceManager.GetString("MI_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string MI_LANGUAGE_ENGLISH {
            get {
                return ResourceManager.GetString("MI_LANGUAGE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string MI_LANGUAGE_RUSSIAN {
            get {
                return ResourceManager.GetString("MI_LANGUAGE_RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string MI_LANGUAGE_UKRAINE {
            get {
                return ResourceManager.GetString("MI_LANGUAGE_UKRAINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string MI_LOG {
            get {
                return ResourceManager.GetString("MI_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string MI_REGISTRATION {
            get {
                return ResourceManager.GetString("MI_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset activation.
        /// </summary>
        internal static string MI_RESET_ACTIVATION_SELECTED {
            get {
                return ResourceManager.GetString("MI_RESET_ACTIVATION_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MI_SAVE {
            get {
                return ResourceManager.GetString("MI_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string MI_SEARCH {
            get {
                return ResourceManager.GetString("MI_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select activated numbers.
        /// </summary>
        internal static string MI_SELECT_ACTIVATED {
            get {
                return ResourceManager.GetString("MI_SELECT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification.
        /// </summary>
        internal static string MI_SEND_NOTIFICATION {
            get {
                return ResourceManager.GetString("MI_SEND_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set activation.
        /// </summary>
        internal static string MI_SET_ACTIVATION_SELECTED {
            get {
                return ResourceManager.GetString("MI_SET_ACTIVATION_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MI_SETTINGS {
            get {
                return ResourceManager.GetString("MI_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call settings.
        /// </summary>
        internal static string MI_SETTINGS_CALL {
            get {
                return ResourceManager.GetString("MI_SETTINGS_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem settings.
        /// </summary>
        internal static string MI_SETTINGS_MODEM {
            get {
                return ResourceManager.GetString("MI_SETTINGS_MODEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MI_VIEW {
            get {
                return ResourceManager.GetString("MI_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The called number {0} was successfully defined as activated..
        /// </summary>
        internal static string MSG_ACTIVATED_NUMBER {
            get {
                return ResourceManager.GetString("MSG_ACTIVATED_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com-port has wrong setup or mobile phone is not connected..
        /// </summary>
        internal static string MSG_COM_PORT_OR_MOBILE_ERROR {
            get {
                return ResourceManager.GetString("MSG_COM_PORT_OR_MOBILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed command: {0}.
        /// </summary>
        internal static string MSG_COMMAND_EXECUTED {
            get {
                return ResourceManager.GetString("MSG_COMMAND_EXECUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response of modem on AT command:{0}.
        /// </summary>
        internal static string MSG_COMMAND_RESPONSE_AT {
            get {
                return ResourceManager.GetString("MSG_COMMAND_RESPONSE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsed code: {0}.
        /// </summary>
        internal static string MSG_COMMAND_RESPONSE_CODE {
            get {
                return ResourceManager.GetString("MSG_COMMAND_RESPONSE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsed code of CEND: {0}.
        /// </summary>
        internal static string MSG_COMMAND_RESPONSE_CODE_CEND {
            get {
                return ResourceManager.GetString("MSG_COMMAND_RESPONSE_CODE_CEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsed code changed on: {0}.
        /// </summary>
        internal static string MSG_COMMAND_RESPONSE_CODE_CHANGED {
            get {
                return ResourceManager.GetString("MSG_COMMAND_RESPONSE_CODE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsed code of CLCC: {0}.
        /// </summary>
        internal static string MSG_COMMAND_RESPONSE_CODE_CLCC {
            get {
                return ResourceManager.GetString("MSG_COMMAND_RESPONSE_CODE_CLCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsed code of CPAS: {0}.
        /// </summary>
        internal static string MSG_COMMAND_RESPONSE_CODE_CPAS {
            get {
                return ResourceManager.GetString("MSG_COMMAND_RESPONSE_CODE_CPAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending SMS for calling phone: {0}.
        /// </summary>
        internal static string MSG_COMMAND_SMS_EXECUTING {
            get {
                return ResourceManager.GetString("MSG_COMMAND_SMS_EXECUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending USSD for calling phone: {0}.
        /// </summary>
        internal static string MSG_COMMAND_USSD_EXECUTING {
            get {
                return ResourceManager.GetString("MSG_COMMAND_USSD_EXECUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure in deleting {0} of selected phone numbers from the list?.
        /// </summary>
        internal static string MSG_DELETE_SELECTED_CONFIRMATION {
            get {
                return ResourceManager.GetString("MSG_DELETE_SELECTED_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        internal static string MSG_DELETION_TITLE {
            get {
                return ResourceManager.GetString("MSG_DELETION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add diapason..
        /// </summary>
        internal static string MSG_DIAPASON_EMPTY {
            get {
                return ResourceManager.GetString("MSG_DIAPASON_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at working with modem..
        /// </summary>
        internal static string MSG_ERROR_MODEM_TITLE {
            get {
                return ResourceManager.GetString("MSG_ERROR_MODEM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the field &apos;{0}&apos;..
        /// </summary>
        internal static string MSG_FIELD_EMPTY {
            get {
                return ResourceManager.GetString("MSG_FIELD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should be a number..
        /// </summary>
        internal static string MSG_FIELD_NOT_NUMBER {
            get {
                return ResourceManager.GetString("MSG_FIELD_NOT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should be in correct format..
        /// </summary>
        internal static string MSG_FIELD_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("MSG_FIELD_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not created. It is possible that user doesn&apos;t have corresponding rights..
        /// </summary>
        internal static string MSG_FILE_WAS_NOT_CREATED {
            get {
                return ResourceManager.GetString("MSG_FILE_WAS_NOT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory.
        /// </summary>
        internal static string MSG_FOLDER_BROWSER_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("MSG_FOLDER_BROWSER_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile phone doesn&apos;t support work with IMEI. Please use another one to start working with program..
        /// </summary>
        internal static string MSG_IMEI_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("MSG_IMEI_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MSG_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("MSG_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using introductory version where you can call at least 5 numbers at one start of program.\nPlease register program..
        /// </summary>
        internal static string MSG_INTRODUCTORY_VERSION {
            get {
                return ResourceManager.GetString("MSG_INTRODUCTORY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of current settings for call processing:.
        /// </summary>
        internal static string MSG_LOG_SETTINGS {
            get {
                return ResourceManager.GetString("MSG_LOG_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port of modem is resetting,.
        /// </summary>
        internal static string MSG_MODEM_PORT_RESET {
            get {
                return ResourceManager.GetString("MSG_MODEM_PORT_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with modem is completed..
        /// </summary>
        internal static string MSG_MODEM_WORK_COMPLETED {
            get {
                return ResourceManager.GetString("MSG_MODEM_WORK_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} is already present in the list and will be missed. Would you like to continue process of list load?.
        /// </summary>
        internal static string MSG_NUMBER_DUPLICATED {
            get {
                return ResourceManager.GetString("MSG_NUMBER_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} has invalid format and will be missed. It must have length with more than 5 chars. Would you like to continue process of list load?.
        /// </summary>
        internal static string MSG_NUMBER_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("MSG_NUMBER_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During work of program there were changes. Do you want to save them?.
        /// </summary>
        internal static string MSG_PROGRAM_DATA_CHANGED {
            get {
                return ResourceManager.GetString("MSG_PROGRAM_DATA_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for program registration!.
        /// </summary>
        internal static string MSG_REGISTRATION_SUCCESSFUL {
            get {
                return ResourceManager.GetString("MSG_REGISTRATION_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong activation key!.
        /// </summary>
        internal static string MSG_REGISTRATION_WRONG {
            get {
                return ResourceManager.GetString("MSG_REGISTRATION_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string MSG_SAVE_TITLE {
            get {
                return ResourceManager.GetString("MSG_SAVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string MSG_SELECT_TEXT_FILE_EXT {
            get {
                return ResourceManager.GetString("MSG_SELECT_TEXT_FILE_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a text file.
        /// </summary>
        internal static string MSG_SELECT_TEXT_FILE_TITLE {
            get {
                return ResourceManager.GetString("MSG_SELECT_TEXT_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem don&apos;t support SMS sending. Uncheck sending of notifications..
        /// </summary>
        internal static string MSG_SMS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("MSG_SMS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error.
        /// </summary>
        internal static string MSG_SYSTEM_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MSG_SYSTEM_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem don&apos;t support USSD sending. Uncheck sending of notifications..
        /// </summary>
        internal static string MSG_USSD_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("MSG_USSD_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should store a number which is not less then {1} seconds..
        /// </summary>
        internal static string MSG_WAIT_ANSWER_LIMIT {
            get {
                return ResourceManager.GetString("MSG_WAIT_ANSWER_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; should store a number which is not less then {1} seconds..
        /// </summary>
        internal static string MSG_WAIT_CALL_LIMIT {
            get {
                return ResourceManager.GetString("MSG_WAIT_CALL_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MSG_WARNING_TITLE {
            get {
                return ResourceManager.GetString("MSG_WARNING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}. You have a registration which is only for IMEI of mobile phone: {1}..
        /// </summary>
        internal static string MSG_WRONG_IMEI_REGISTRATION {
            get {
                return ResourceManager.GetString("MSG_WRONG_IMEI_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of found activated numbers: {0}.
        /// </summary>
        internal static string STAT_SESSION_ACTIVATED_COUNT {
            get {
                return ResourceManager.GetString("STAT_SESSION_ACTIVATED_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session state for call:.
        /// </summary>
        internal static string STAT_SESSION_HEADER {
            get {
                return ResourceManager.GetString("STAT_SESSION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of processed numbers: {0}.
        /// </summary>
        internal static string STAT_SESSION_PROCESSED_COUNT {
            get {
                return ResourceManager.GetString("STAT_SESSION_PROCESSED_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of remained numbers: {0}.
        /// </summary>
        internal static string STAT_SESSION_REMAINED_COUNT {
            get {
                return ResourceManager.GetString("STAT_SESSION_REMAINED_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0:D2}:{1:D2}.
        /// </summary>
        internal static string STAT_SESSION_REMAINED_TIME {
            get {
                return ResourceManager.GetString("STAT_SESSION_REMAINED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated: {0}.
        /// </summary>
        internal static string STAT_TELEPHONE_ACTIVATED_COUNT {
            get {
                return ResourceManager.GetString("STAT_TELEPHONE_ACTIVATED_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone count: {0}.
        /// </summary>
        internal static string STAT_TELEPHONE_COUNT {
            get {
                return ResourceManager.GetString("STAT_TELEPHONE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string WND_ABOUT_FORM_TITLE {
            get {
                return ResourceManager.GetString("WND_ABOUT_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call settings.
        /// </summary>
        internal static string WND_CALL_SETTINGS_FORM_TITLE {
            get {
                return ResourceManager.GetString("WND_CALL_SETTINGS_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment for phone number: {0}.
        /// </summary>
        internal static string WND_COMMENT_FORM_TITLE {
            get {
                return ResourceManager.GetString("WND_COMMENT_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string WND_KEY_FORM_TITLE {
            get {
                return ResourceManager.GetString("WND_KEY_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defining of activated telephones.
        /// </summary>
        internal static string WND_MAIN_FORM_TITLE {
            get {
                return ResourceManager.GetString("WND_MAIN_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem settings.
        /// </summary>
        internal static string WND_MODEM_SETTINGS_FORM_TITLE {
            get {
                return ResourceManager.GetString("WND_MODEM_SETTINGS_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string WND_SEARCH_FORM_TITLE {
            get {
                return ResourceManager.GetString("WND_SEARCH_FORM_TITLE", resourceCulture);
            }
        }
    }
}
